services:
  #nombre del servicio
  api_node24_experimentojs:
    build: . #construye basado en dockerfile
    container_name: api_node24_experimetojs #nombre del contenedor
    ports:
      - "3000:3000" #de mi puerto 3000 al 3000 del contenedor
    volumes:
      #hacemos un copy manual de cada ruta para que no colisione con pnpm, un volumen anonimo causa condlicto en windows
      - ./index.js:/home/app/index.js
      - ./src:/home/app/src
      - ./utils:/home/app/utils
      - ./package.json:/home/app/package.json
      - ./data:/home/app/data
      - ./config:/home/app/config
      - ./services:/home/app/services
      - ./.env:/home/app/.env

    networks:
      - experimento_network #una red interna de docker para experimentos

  #una basesita para no andar manipulando jsons
  dv_postgres17:
    image: postgres:17.11-alpine3.24 #postgres 17
    container_name: dv_postgres17 #nombramos al contenedor para ubicarlo en la red
    environment:
      #variables minimas requeridas (ahora importadas desde tu .env o las de defecto que ponemos aquí)
      POSTGRES_USER: ${DB_ROOT_USER:-admin}
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD:-quierodostacos17}
      POSTGRES_DB: ${POSTGRES_DB:-experimentsdb}
    ports:
      - "5432:5432" #puerto default para db
    volumes:
      - db_posgre17:/var/lib/postgresql/data #ruta al almacenamiento postgres
      - ./db_init:/docker-entrypoint-initdb.d # <--- NUEVA LÍNEA PARA EL INIT
    networks:
      - experimento_network #misma red para que se vean

networks:
  experimento_network:
    #red interna para experimentos
    driver: bridge

volumes:
  db_posgre17: #volumen para perseverar los datos de la db
